name: Build & Test
on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
          submodules: true

      - name: Set SHAs
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: master

      - name: Install dependencies
        run: pnpm i

      - name: Lint
        run: pnpm nx workspace-lint

      - name: Format
        run: pnpm nx format:check

      - name: Lint all
        run: pnpm nx affected --target=lint --parallel=3

      - name: Lint all (CI)
        run: pnpm nx affected --target=test --parallel=3 --configuration=ci

      - name: Build
        run: pnpm nx affected --target=build --parallel=3
