name: CI
on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: pnpm i

      - run: pnpm nx workspace-lint
      - run: pnpm nx format:check
      - run: pnpm nx affected --target=lint --parallel=3
      - run: pnpm nx affected --target=test --parallel=3 --configuration=ci
      - run: pnpm nx affected --target=build --parallel=3
